### ISSUE TITLE
Android 8.0 : IllegalStateException: Not allowed to start service Intent com.google.android.gms.analytics.ANALYTICS_DISPATCH 

### ISSUE THREAD

**Issue by SteveGrosbois** [segment-integrations/analytics-android-integration-google-analytics#15]
Hi !

There is new IllegalStateExceptions throwing on Android 8.0 : 
```
java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.gms.analytics.ANALYTICS_DISPATCH cmp=com.mypackage/com.google.android.gms.analytics.AnalyticsService }: app is in background uid UidRecord{6e20b26 u0a298 CEM  idle procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
        at android.app.ContextImpl.startService(ContextImpl.java:1484)
        at android.content.ContextWrapper.startService(ContextWrapper.java:663)
        at com.google.android.gms.internal.measurement.i.c(Unknown:36)
        at com.google.android.gms.analytics.c.f(Unknown:8)
        at com.segment.analytics.android.integrations.google.analytics.DefaultGoogleAnalytics.dispatchLocalHits(SourceFile:26)
        at com.segment.analytics.android.integrations.google.analytics.GoogleAnalyticsIntegration.flush(SourceFile:331)
        at com.segment.analytics.IntegrationOperation$13.run(SourceFile:275)
        at com.segment.analytics.Analytics.performRun(SourceFile:1464)
        at com.segment.analytics.Analytics$4$1.run(SourceFile:455)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by kwiky** [comment]
May be one of the causes : `src/main/java/com/segment/analytics/android/integrations/google/analytics/GoogleAnalyticsIntegration.java uses or overrides a deprecated API.`

**Comment by Kiran89kumar** [comment]
Any update?

**Comment by GeenyH** [comment]
Any update? Please.

**Comment by ankitguptag18** [comment]
Any info would be appreciated.

Expected Timeline of the fix?
Priority of the bug?
Will the Bug be fixed?
Will the issue won't be fixed in favor of Firebase Analytics?

**Comment by fredgit** [comment]
Similar reproduce step: https://stackoverflow.com/a/48166636

**Comment by gpandroid90** [comment]
got the same issue with version 16.0.6.

**Comment by atuledate007** [comment]
CampaignTrackingService 
remove from manifest

**Comment by NitinPraksash9911** [comment]
Still facing this issue

```
Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.gms.analytics.ANALYTICS_DISPATCH cmp=app.trell/com.google.android.gms.analytics.AnalyticsService }: app is in background uid UidRecord{5ab8477 u0a780 CAC  bg:+2m31s858ms idle change:cached procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1687)
       at android.app.ContextImpl.startService(ContextImpl.java:1632)
       at android.content.ContextWrapper.startService(ContextWrapper.java:683)
       at com.google.android.gms.internal.gtm.zzbq.zzc(zzbq.java:7)
       at com.google.android.gms.analytics.GoogleAnalytics.dispatchLocalHits(GoogleAnalytics.java:2)
       at app.geochat.revamp.application.Trell.trackScreenView(Trell.java:287)
       at app.geochat.revamp.utils.Utils.trackActivity(Utils.java:2561)
       at app.geochat.revamp.utils.Utils.trackActivity(Utils.java:2551)
       at app.geochat.revamp.deeplink.DeepLinkHandler.onCreate(DeepLinkHandler.java:100)
       at android.app.Activity.performCreate(Activity.java:7955)
       at android.app.Activity.performCreate(Activity.java:7944)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```
